development:
  host: localhost
  port: 27017
  database: rm35
  logfile: development.log

production:
  host: localhost
  port: 27017
  database: rm35
  logfile: production.log

environment: development